version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && cd /export/rails/site_1 && bundle install &&  bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./site_1:/export/rails/site_1
    ports:
      - "3000:3000"
    container_name: site_1